name: lai-homepage
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - target: "3000"
        published: "3011"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /app/config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
x-casaos:
  architectures:
    - amd64
    - arm
  main: homepage
  description:
    en_us: 'Homepage is a dashboard for your server. It is a web application that you can access from any device on your network. It allows you to monitor your server, manage your downloads, and more.'
  tagline:
    en_us: 'A dashboard for your server'
  developer: 'Homepage'
  author: eudard
  icon: 'https://gethomepage.dev/v0.7.3/assets/light_squircle@2x.png'
  thumbnail: ''
  title:
    en_us: 'Homepage'
  category: LocalAiStore
  port_map: '3011'
