name: linuxserver-jellyfin
services:
  app:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 15869M
    environment:
      - JELLYFIN_PublishedServerUrl=
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Prague
    image: linuxserver/jellyfin:10.8.13
    labels:
      icon: https://raw.githubusercontent.com/eudard/CasaOS-LocalAI-AppStore/master/Apps/jellyfin/jellyfin.png
    ports:
      - target: 8096
        published: "10096"
        protocol: tcp
      - target: 8920
        published: "10920"
        protocol: tcp
      - target: 7359
        published: "7359"
        protocol: udp
      - target: 1900
        published: "11900"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/jellyfin/config
        target: /config
      - type: bind
        source: /DATA/Media/TV Shows
        target: /data/tvshows
      - type: bind
        source: /DATA/Media/Movies
        target: /data/movies
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: JELLYFIN_PublishedServerUrl
          description:
            en_us: Set the autodiscovery response domain or IP address.
      ports:
        - container: "8096"
          description:
            en_us: Webui - Default 8096 (HTTP)
        - container: "8920"
          description:
            en_us: Webui - Default 8920 (HTTPS) (Optional)
        - container: "1900"
          description:
            en_us: Service Discovery (Optional)
      volumes:
        - container: /config
          description:
            en_us: Appdata
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
    container_name: ""
networks:
  default:
    name: linuxserver-jellyfin_default
x-casaos:
  architectures:
    - amd64
    - arm64
  author: WisdomSky
  category: LinuxServer.io
  description:
    en_us: "Visit homepage: https://hub.docker.com/r/linuxserver/jellyfin/"
  developer: LinuxServer.io
  hostname: ""
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png
  index: /
  main: app
  port_map: "10096"
  project_url: https://github.com/jellyfin/jellyfin#jellyfin
  scheme: http
  store_app_id: linuxserver-jellyfin
  tagline:
    en_us: "A Free Software Media System that puts you in control of managing and
      streaming your media. It is an alternative to the proprietary Emby and
      Plex, to provide media from a dedicated server to end-user devices via
      multiple apps. Jellyfin is descended from Emby's 3. 5. 2 release and
      ported to the. NET Core framework to enable full cross-platform support.
      There are no strings attached, no premium licenses or features, and no
      hidden agendas: just a team who want to build something better and work
      together to achieve it."
  thumbnail: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/banner-logo-solid.svg?sanitize=true
  title:
    custom: ""
    en_us: Jellyfin
