name: metabase
version: "3.9"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: Metabase
    hostname: metabase
    mem_limit: 3g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: "<YOUR_UID>:<YOUR_GID>" # Replace with your user and group ID
    healthcheck:
      test: curl --fail -I http://192.168.31.50:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    ports:
      - 6400:3000
    volumes:
      - /DATA/AppData/$AppID/plugins:/plugins:rw

    environment:
      TZ: "Europe/Prague"
      JAVA_TIMEZONE: "Europe/Prague"
      MUID: "1026"
      MGID: "100"
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "metabase"
      MB_DB_PORT: "5432"
      MB_DB_USER: "metabaseuser"
      MB_DB_PASS: "metabasepass"
      MB_DB_HOST: "metabase-db"
      MB_EMAIL_FROM_ADDRESS: "Your-own-gmail-address"
      MB_EMAIL_FROM_NAME: "Metabase"
      MB_EMAIL_REPLY_TO: "true"
      MB_EMAIL_SMTP_USERNAME: "Your-own-gmail-address"
      MB_EMAIL_SMTP_PASSWORD: "Your-own-app-password"
      MB_EMAIL_SMTP_HOST: "smtp.gmail.com"
      MB_EMAIL_SMTP_SECURITY: "ssl"
      MB_EMAIL_SMTP_PORT: "465"
      MB_SITE_URL: "http://192.168.31.50"
    restart: on-failure:5
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: "The timezone to use"
        - container: JAVA_TIMEZONE
          description:
            en_us: "The timezone to use"
        - container: MB_DB_USER
          description:
            en_us: "The username to use for the database"
        - container: MB_DB_PASS
          description:
            en_us: "The password to use for the database"
        - container: MB_EMAIL_FROM_ADDRESS
          description:
            en_us: "The email address to use for sending emails"
        - container: MB_EMAIL_FROM_NAME
          description:
            en_us: "The name to use for sending emails"
        - container: MB_EMAIL_SMTP_USERNAME
          description:
            en_us: "SMTP username to use for sending emails"
        - container: MB_EMAIL_SMTP_PASSWORD
          description:
            en_us: "SMTP password to use for sending emails"
        - container: MB_EMAIL_SMTP_HOST
          description:
            en_us: "SMTP host to use for sending emails"
        - container: MB_EMAIL_SMTP_SECURITY
          description:
            en_us: "SMTP security to use for sending emails (ssl or tls)"
        - container: MB_EMAIL_SMTP_PORT
          description:
            en_us: "SMTP port to use for sending emails (465 for ssl, 587 for tls)"
        - container: MB_SITE_URL
          description:
            en_us: "The URL to use for sending emails"

x-casaos:
  architectures:
    - amd64
    - arm
  main: metabase
  description:
    en_us: "Metabase is the easy, open source way for everyone in your company to ask questions and learn from data."
  tagline:
    en_us: "The fastest, easiest way to share data and analytics inside your company. An open source Business Intelligence server you can install in 5 minutes that connects to MySQL, PostgreSQL, MongoDB and more! Anyone can use it to build charts, dashboards and nightly email reports."
  developer: "Metabase, Inc."
  author: eudard
  icon: ""
  thumbnail: ""
  title:
    en_us: Metabase
  category: "Productivity"
  port_map: "6400"
