version: "3.9"
services:
  db:
    image: postgres
    container_name: Metabase-DB
    hostname: metabase-db
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    #user: 1026:100
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "metabase", "-U", "metabaseuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /DATA/AppData/metabasedb/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabaseuser
      POSTGRES_PASSWORD: metabasepass
    restart: on-failure:5

  metabase:
    image: metabase/metabase:latest
    container_name: Metabase
    hostname: metabase
    mem_limit: 3g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    #user: 1026:100
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    ports:
      - 6400:3000
    volumes:
      - /DATA/AppData/metabase/plugins:/plugins:rw
    environment:
      TZ: Europe/Bucharest
      JAVA_TIMEZONE: Europe/Bucharest
      #MUID: 1026
      #MGID: 100
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabaseuser
      MB_DB_PASS: metabasepass
      MB_DB_HOST: metabase-db
      MB_EMAIL_FROM_ADDRESS: Your-own-gmail-address
      MB_EMAIL_FROM_NAME: Metabase
      MB_EMAIL_REPLY_TO: true
      MB_EMAIL_SMTP_USERNAME: Your-own-gmail-address
      MB_EMAIL_SMTP_PASSWORD: Your-own-app-password
      MB_EMAIL_SMTP_HOST: smtp.gmail.com
      MB_EMAIL_SMTP_SECURITY: ssl
      MB_EMAIL_SMTP_PORT: 465
      MB_SITE_URL: metabase.yourname.synology.me

    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
