version: '3'
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7755:7700"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/meilisearch:/meili_data
x-casaos:
  architectures:
    - amd64
    - arm64
  main: meilisearch
  author: "eudard"
  developer: "meilisearch"
  category: "SelfhostAI"
  icon: "https://avatars.githubusercontent.com/u/43250847?s=280&v=4"
  port_map: "7755"
  title:
    en_us: "MeiliSearch"
  description:
    en_us: "A lightning-fast and hyper-relevant search engine that fits effortlessly into your workflow."
