version: '3.3'
services:
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    ports:
      - '3006:3000'
      - '3007:3001'
    image: openspeedtest/latest
    x-casaos:
      ports:
        - container: "3000"
          description:
            en_us: "OpenSpeedTest - Standard port"
        - container: "3001"
          description:
            en_us: "OpenSpeedTest - Additional port"
x-casaos:
  architectures:
    - amd64
    - arm64
  main: speedtest
  description:
    en_us: "OpenSpeedTest is a web-based speed test for your internet connection."
  tagline:
    en_us: "Internet Speed Test"
  developer: "OpenSpeedTest"
  author: "eudard"
  icon: ""
  thumbnail: ""
  title:
    en_us: "OpenSpeedTest"
  category: "Network Tools"
  port_map: "3006"

# V případě potřeby můžete přidat definice dalších sítí nebo konfigurací.
