name: localai-serge
services:
  serge:
    command:
      - /bin/bash
      - -c
      - /usr/src/app/deploy.sh
    environment:
      - GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
      - LANG=C.UTF-8
      - NODE_ENV=production
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PYTHON_GET_PIP_SHA256=22b849a10f86f5ddf7ce148ca2a31214504ee6c83ef626840fde6e5dcd809d11
      - PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/c6add47b0abf67511cdfb4734771cbab403af062/public/get-pip.py
      - PYTHON_PIP_VERSION=23.2.1
      - PYTHON_SETUPTOOLS_VERSION=65.5.1
      - PYTHON_VERSION=3.11.6
      - TZ=Etc/UTC
    image: ghcr.io/serge-chat/serge:0.5.0
    ports:
      - target: 8008
        published: "8008"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/db:/data/db
      - /DATA/AppData/$AppID/weights:/usr/src/app/weights
    x-casaos:
      envs:
        - container: PATH
          description:
            en_us: ""
        - container: LANG
          description:
            en_us: ""
        - container: GPG_KEY
          description:
            en_us: ""
        - container: PYTHON_VERSION
          description:
            en_us: ""
        - container: PYTHON_PIP_VERSION
          description:
            en_us: ""
        - container: PYTHON_SETUPTOOLS_VERSION
          description:
            en_us: ""
        - container: PYTHON_GET_PIP_URL
          description:
            en_us: ""
        - container: PYTHON_GET_PIP_SHA256
          description:
            en_us: ""
        - container: NODE_ENV
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "8008"
          description:
            en_us: ""
      volumes:
        - container: /data/db
          description:
            en_us: ""
        - container: /usr/src/app/weights
          description:
            en_us: ""
    container_name: ""
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 15873M
x-casaos:
  architectures:
    - amd64
    - arm
  main: localai-serge
  description:
    en_us: 'Custom Local AI instances'
  tagline:
    en_us: 'LLama on your local network'
  developer: ''
  author: eudard
  icon: https://raw.githubusercontent.com/eudard/CasaOS-LocalAI-AppStore/master/Apps/serge/icon_bg.png
  thumbnail: https://raw.githubusercontent.com/eudard/CasaOS-LocalAI-AppStore/master/Apps/serge/screenshot-1.png
  title:
    en_us: Serge
  category: SelfhostAI
  port_map: "8008"
