version: '3'
services:
  openwebui:
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
    image: ghcr.io/open-webui/open-webui:latest
    labels:
      icon: https://avatars.githubusercontent.com/u/158137808?s=280&v=4
    ports:
      - "30000:8080"
    restart: always
    volumes:
      - /DATA/AppData/openwebui:/app/backend/data
x-casaos:
  architectures:
    - amd64
    - arm64
  main: openwebui
  description:
    en_us: "Open source web interface for local AI services"
  tagline:
    en_us: "OpenWebUI"
  developer: "OpenWebUI"
  author: "eudard"
  icon: "https://avatars.githubusercontent.com/u/158137808?s=280&v=4"
  thumbnail: "https://github.com/open-webui/open-webui/raw/main/demo.gif"
  title:
    en_us: "OpenWebUI"
  category: "SelfhostAI"
  port_map: "30000"
